server:
   port: 8081

spring:
   application:
      name: carro-service
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/microservice_third
      username: root
      password: 123456
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
